# =====================================================
# Stage 1: Install dependencies
# =====================================================
FROM node:20-alpine AS deps

WORKDIR /app

# Install only production-relevant packages (faster)
COPY package.json package-lock.json ./
RUN npm ci

# =====================================================
# Stage 2: Build the Next.js app
# =====================================================
FROM node:20-alpine AS builder

WORKDIR /app

# NEXT_PUBLIC_* vars are embedded at BUILD TIME by Next.js.
# Pass them as build arguments so the bundle contains the correct values.
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_MAP_CENTER_LAT=40.4168
ARG NEXT_PUBLIC_MAP_CENTER_LNG=-3.7038
ARG NEXT_PUBLIC_MAP_ZOOM=13

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_MAP_CENTER_LAT=$NEXT_PUBLIC_MAP_CENTER_LAT
ENV NEXT_PUBLIC_MAP_CENTER_LNG=$NEXT_PUBLIC_MAP_CENTER_LNG
ENV NEXT_PUBLIC_MAP_ZOOM=$NEXT_PUBLIC_MAP_ZOOM

# Disable Next.js telemetry in CI/CD
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# =====================================================
# Stage 3: Production runtime (minimal image)
# =====================================================
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Port must match npm start script (-p 8547)
ENV PORT=8547
ENV HOSTNAME="0.0.0.0"

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy only what Next.js needs to run
COPY --from=builder /app/public ./public

# Automatically leverage Next.js output file tracing for minimal image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 8547

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
